# Generated by Django 3.2 on 2021-04-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='parcel_cost',
            field=models.IntegerField(default=0),
        ),
    ]
